version: "3"
services:
  ngx:
    container_name:  ngx
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./html:/usr/share/nginx/html"