version: '3'

services:
  zoo1:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    hostname: zoo1
    ports:
      - "2181:2181"
    container_name: zookeeper
    volumes:
      - "./zoo1/data:/opt/zookeeper-3.4.13/data"

  kafka1:
    image: wurstmeister/kafka
    volumes:
            - "./kafka1:/kafka"
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.72.90
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "stream-in:2:1,stream-out:2:1"
      JMX_PORT: 9999
    depends_on:
      - zoo1
    container_name: kafka1
    hostname: kafka1


  kafka2:
    image: wurstmeister/kafka
    volumes:
            - "./kafka2:/kafka"
    restart: unless-stopped
    ports:
      - "9093:9092"
      - "9998:9998"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.72.90
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      JMX_PORT: 9998
    depends_on:
      - zoo1
    container_name: kafka2
    hostname: kafka2

  kafka-manager:
      restart: unless-stopped
      container_name: kafka-manager
      image: hlebalbau/kafka-manager:stable
      ports:
        - "9000:9000"
      environment:
        ZK_HOSTS:  zoo1:2181
        APPLICATION_SECRET: "random-secret"
      command: -Dpidfile.path=/dev/null

    
