version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./data:/data/db"
    restart: unless-stopped
    network_mode: bridge


# networks:
#   outside:
#     external:
#       true
#     name:
#       bridge